export type LoginLocale = "zh-CN" | "en-US";

const zhCnLoginCopy = {
  brandName: "CAAIS",
  brandSubline: "Cognitive Apprenticeship AI System",
  welcome: "欢迎来到 CAAIS",
  languageLabel: "语言",
  loginModeLabel: "登录方式",
  accountLogin: "账号密码登录",
  accountLabel: "账号",
  accountPlaceholder: "学生账号",
  passwordLabel: "密码",
  passwordPlaceholder: "请输入密码",
  submit: "立即登录",
  forgotPassword: "忘记密码？",
  backToLogin: "返回登录",
  resetPassword: "重置密码",
  resetEmailLabel: "账号邮箱",
  resetEmailPlaceholder: "请输入账号邮箱",
  resetSubmit: "发送重置邮件",
  resetSuccess: "如果该账号存在，重置邮件将会发送到对应邮箱。",
  setPassword: "设置密码",
  newPasswordLabel: "新密码",
  newPasswordPlaceholder: "至少 10 个字符",
  confirmPasswordLabel: "确认密码",
  confirmPasswordPlaceholder: "再次输入密码",
  setPasswordSubmit: "保存密码",
  setPasswordSuccess: "密码已更新，请使用新密码登录。",
  consentCheckboxLabel: "我确认已阅读并同意用户协议和隐私政策，未成年学习者已取得家长或监护人同意。",
  terms: "用户协议",
  privacy: "隐私政策",
  consentRequiredError: "请先确认用户协议、隐私政策和必要的监护人同意。",
  emptyError: "请输入账号和密码。",
  emailError: "请输入账号邮箱。",
  emailInvalidError: "请输入有效的账号邮箱。",
  passwordLengthError: "密码至少需要 10 个字符。",
  passwordMismatchError: "两次输入的密码不一致。",
  invalidError: "账号或密码不匹配，请使用已授权的 CAAIS 账号登录。",
  rateLimitError: "请求过于频繁，请稍后再试。",
  passwordTokenInvalidError: "该密码设置链接无效或已过期，请重新申请。",
  passwordInputInvalidError: "密码请求内容无效，请检查后重试。",
  passwordRequestTooLargeError: "密码请求内容过长，请缩短后重试。",
  serverError: "登录服务暂时不可用，请稍后再试。",
  researchLogoutAckWarning: "账号已安全退出，但最终研究事件未获确认。请告知研究人员，且不要将本次实验标记为完成。",
  showPassword: "显示密码",
  hidePassword: "隐藏密码",
  saving: "保存中...",
  sending: "发送中...",
  signingIn: "登录中...",
  consentBasisPrefix: "",
  consentBasisConnector: " 和 ",
  consentBasisSuffix: " 将作为本次登录确认的依据。",
  protectedSpaceNotice: "继续登录即使用当前账号进入受保护的学习空间。",
};

const enUsLoginCopy: typeof zhCnLoginCopy = {
  brandName: "CAAIS",
  brandSubline: "Cognitive Apprenticeship AI System",
  welcome: "Welcome to CAAIS",
  languageLabel: "Language",
  loginModeLabel: "Sign-in method",
  accountLogin: "Account and password",
  accountLabel: "Account",
  accountPlaceholder: "Student account or email",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter your password",
  submit: "Sign in",
  forgotPassword: "Forgot password?",
  backToLogin: "Back to sign in",
  resetPassword: "Reset password",
  resetEmailLabel: "Account email",
  resetEmailPlaceholder: "Enter your account email",
  resetSubmit: "Send reset email",
  resetSuccess: "If the account exists, a password-reset email will be sent to its address.",
  setPassword: "Set password",
  newPasswordLabel: "New password",
  newPasswordPlaceholder: "At least 10 characters",
  confirmPasswordLabel: "Confirm password",
  confirmPasswordPlaceholder: "Enter the password again",
  setPasswordSubmit: "Save password",
  setPasswordSuccess: "Your password has been updated. Sign in with the new password.",
  consentCheckboxLabel: "I have read and agree to the Terms of Use and Privacy Policy. A parent or guardian has consented for any learner who is a minor.",
  terms: "Terms of Use",
  privacy: "Privacy Policy",
  consentRequiredError: "Confirm the Terms of Use, Privacy Policy, and any required parent or guardian consent before signing in.",
  emptyError: "Enter your account and password.",
  emailError: "Enter your account email.",
  emailInvalidError: "Enter a valid account email.",
  passwordLengthError: "The password must contain at least 10 characters.",
  passwordMismatchError: "The passwords do not match.",
  invalidError: "The account or password did not match. Use an authorized CAAIS account.",
  rateLimitError: "Too many requests. Try again later.",
  passwordTokenInvalidError: "This password link is invalid or has expired. Request a new one.",
  passwordInputInvalidError: "The password request is invalid. Check it and try again.",
  passwordRequestTooLargeError: "The password request is too large. Shorten it and try again.",
  serverError: "The sign-in service is temporarily unavailable. Try again later.",
  researchLogoutAckWarning: "You were signed out securely, but the final research event was not acknowledged. Tell the researcher and do not mark this session complete.",
  showPassword: "Show password",
  hidePassword: "Hide password",
  saving: "Saving...",
  sending: "Sending...",
  signingIn: "Signing in...",
  consentBasisPrefix: "The ",
  consentBasisConnector: " and ",
  consentBasisSuffix: " are the basis for this sign-in acknowledgement.",
  protectedSpaceNotice: "Continue with this account to enter the protected learning space.",
};

export const loginCopyByLocale: Record<LoginLocale, typeof zhCnLoginCopy> = {
  "zh-CN": zhCnLoginCopy,
  "en-US": enUsLoginCopy,
};
