import type { Locale } from "@/data/aais";
import type { LearningCopy } from "@/components/pages/learning/learning-copy-types";

export type { LearningCopy } from "@/components/pages/learning/learning-copy-types";

export const learningCopyByLocale: Record<Locale, LearningCopy> = {
  "zh-CN": {
    main: {
      heading: "CAAIS 学习工作台",
      description: "使用智能导学、内容展示和文档编辑完成认知学徒学习任务。",
    },
    brand: {
      logoLabel: "CAAIS 标志",
      accountMenu: (displayName) => `${displayName} 账户菜单`,
      avatar: (displayName) => `${displayName} 原创英雄人脸头像`,
      accountInfo: (displayName) => `${displayName} 账户信息`,
      exportLearnerData: "导出学习数据",
      deleteLearnerData: "删除学习数据",
      signOut: "退出",
    },
    guide: {
      busy: "智能导学处理中...",
      readingFiles: "文件正在读取...",
      quickStarts: "元认知快速开始",
      chooseFiles: "选择上传文件",
      uploadFile: "上传文件",
      inputLabel: "向智能导学输入你的想法",
      inputPlaceholder: "输入你的想法...",
      send: "发送",
      uploadedFiles: "已上传文件",
      removeFile: (fileName) => `移除 ${fileName}`,
      localScaffold: "本地安全支架",
      providerFailureTitle: "AI 暂时降级",
      providerFailureMessage: "实时 AI 链路暂时不可用。你的问题仍保留在本页，可直接重试。",
      guardrailFailureTitle: "这次问题无法提交给 AI",
      guardrailFailureMessage: "请换一种表述后再试。",
      configurationFailureTitle: "AI 服务配置未就绪",
      configurationFailureMessage: "实时 AI 服务尚未就绪。你的问题仍保留在本页，请凭支持码联系管理员。",
      connectionFailureTitle: "连接中断，尚未确认保存",
      connectionFailureMessage: "你的问题仍保留在本页。恢复网络后可直接重试。",
      unknownFailureTitle: "AI 暂时无法回复",
      unknownFailureMessage: "你的问题仍保留在本页，可稍后重试；如问题持续，请提供支持码。",
      supportCode: (diagnosticId) => `支持码：${diagnosticId}`,
      copySupportCode: "复制支持码",
      supportCodeCopied: "支持码已复制",
      supportCodeCopyFailed: "复制失败，请手动选择支持码。",
      retryAction: "重试",
      rewriteAction: "改写问题",
      retryQuestion: "重试这个问题",
      rewriteQuestion: "改写这个问题",
      assistant: "AI 助教",
      avatar: (_agentId, label) => `${label}大学教育风格头像`,
      attachmentUnavailable: "上传文件不可用。",
      inputRequired: "请输入你的想法后再发送。",
      requestIdentityUnavailable: "当前浏览器无法安全创建请求标识。请升级浏览器后再试。",
      requestAccepted: "CAAIS 已收到，多智能体链路正在处理。",
      attachmentLimit: (maxFiles) => `一次最多上传 ${maxFiles} 个文件。`,
      fileReadFailed: "文件未能读取。",
      agentLabels: {
        A1: "小张",
        A2: "教授",
        A3: "监督智能体",
        A4: "反思智能体",
      },
    },
    content: {
      resize: "调整内容展示区域宽度",
      panel: "学习内容与文档",
      displayTab: "内容展示",
      editorTab: "文档编辑",
      saveAndClose: "保存并关闭",
      downloading: "下载中...",
      download: "下载到本地",
      displayNav: "内容展示",
      backToDisplay: "返回内容展示",
      back: "返回",
      documentFolder: (title) => `历史文档文件夹：${title}`,
      items: {
        platform: {
          label: "平台介绍",
          body: "CAAIS平台是一个基于认知学徒理论搭建的，AI赋能的学习平台……",
        },
        theory: {
          label: "任务卡片",
          body: "按顺序完成认知学徒任务；完成当前任务后，下一个任务才会解锁。",
        },
        history: {
          label: "历史文档",
          body: "历史文档用于保存学习过程、重要资料和后续 pilot study 可回顾的记录。",
        },
      },
      taskCards: {
        listLabel: "认知学徒任务卡片",
        progress: (completed, total) => `已完成 ${completed}/${total} 个任务`,
        ordinal: (index) => `任务 ${index}`,
        phase: {
          training: "训练任务",
          practice: "练习任务",
        },
        status: {
          locked: "已锁定",
          available: "可开始",
          active: "进行中",
          completed: "已完成",
        },
        lockedHint: "完成上一任务后解锁",
        enter: "进入任务",
        continue: "继续任务",
        review: "查看任务",
        complete: "完成任务",
        completing: "处理中...",
        actionFailed: "任务状态更新失败，请稍后重试。",
        lockedButton: (title) => `${title}，已锁定`,
        enterButton: (title) => `进入任务：${title}`,
        continueButton: (title) => `继续任务：${title}`,
        reviewButton: (title) => `查看任务：${title}`,
        completeButton: (title) => `完成任务：${title}`,
      },
    },
    editor: {
      titleLabel: "文档标题",
      titlePlaceholder: "输入标题...",
      toolbarLabel: "文档格式工具",
      fontLabel: "字体",
      fontFamilies: {
        system: "默认",
        serif: "衬线",
        mono: "等宽",
      },
      sizeLabel: "字号",
      bold: "加粗",
      italic: "斜体",
      underline: "下划线",
      alignLeft: "左对齐",
      alignCenter: "居中",
      alignRight: "右对齐",
      bulletList: "项目符号",
      numberedList: "编号列表",
      heading1: "一级标题",
      heading2: "二级标题",
      heading3: "三级标题",
      emptyPrompt: "在这里开始记录...",
      inputLabel: "在这里写下任务理解、计划、执行过程或最终产出。",
    },
    document: {
      saveQueuedWhileSaving: "正在保存文档，最新更改已排队。",
      saveResearchPaused: "研究记录连接已暂停，文档更改仍待保存。",
      saving: "正在保存文档...",
      saved: "文档已保存。",
      saveFailed: "任务过程记录未能保存到后端。",
      archiveFailed: "文档未能归档，工作区内容已保留。",
      saveQueued: "文档更改待保存。",
      downloadPreparing: "正在准备下载...",
      downloadReady: "文档下载已准备。",
      downloadFailed: "文档下载未能完成，请稍后重试。",
      justSaved: "刚刚保存",
      untitled: "未命名文档",
    },
    workspace: {
      sessionUnavailable: "学习记录服务暂时不可用，本页会保留当前输入但不会完成持久化。",
    },
    account: {
      waitForOperation: "请等待当前保存、下载或智能体操作完成后再退出。",
      waitForExportOperation: "请等待当前保存、下载或智能体操作完成后再导出学习数据。",
      signingOut: "正在退出...",
      researchSyncRequired: "研究事件尚未安全同步，请保持联网并稍后重试退出。",
      signOutFailed: "退出未完成，服务器会话仍保持有效。请恢复连接后重试。",
      exporting: "正在导出学习数据...",
      exported: "学习数据已导出。",
      exportFailed: "学习数据导出未能完成，请稍后重试。",
      deleteConfirmation: "确定要删除当前学习数据吗？此操作会清除你的学习记录，但不会删除账号。",
      deleting: "正在删除学习数据...",
      deleted: "学习数据已删除。",
      deleteFailed: "学习数据删除未能完成，请稍后重试。",
    },
    researchBoundary: {
      heading: "CAAIS 研究会话保护",
      initializing: "正在建立受控研究会话，请稍候。",
      offlineOrTemporary: "研究记录连接暂时不可用。为避免产生未记录操作，学习工作台已暂停，并将在连接恢复后自动继续。",
      terminalBlocked: "本次研究会话不可继续。请停止操作并联系研究人员。",
      safeExit: "安全退出到登录页",
      safeExiting: "正在安全退出...",
      safeExitFailed: "安全退出暂时失败，请恢复连接后重试。",
    },
  },
  "en-US": {
    main: {
      heading: "CAAIS Learning Workspace",
      description: "Use AI guidance, learning content, and document editing to complete Cognitive Apprenticeship learning tasks.",
    },
    brand: {
      logoLabel: "CAAIS logo",
      accountMenu: (displayName) => `${displayName} account menu`,
      avatar: (displayName) => `${displayName} original hero avatar`,
      accountInfo: (displayName) => `${displayName} account information`,
      exportLearnerData: "Export learning data",
      deleteLearnerData: "Delete learning data",
      signOut: "Sign out",
    },
    guide: {
      busy: "AI guide is thinking...",
      readingFiles: "Reading files...",
      quickStarts: "Metacognitive quick starts",
      chooseFiles: "Choose files to upload",
      uploadFile: "Upload file",
      inputLabel: "Share your thinking with the AI guide",
      inputPlaceholder: "Share your thoughts...",
      send: "Send",
      uploadedFiles: "Uploaded files",
      removeFile: (fileName) => `Remove ${fileName}`,
      localScaffold: "Local safe scaffold",
      providerFailureTitle: "AI is temporarily degraded",
      providerFailureMessage: "The live AI chain is temporarily unavailable. Your question remains on this page, and you can retry it.",
      guardrailFailureTitle: "This question could not be submitted to AI",
      guardrailFailureMessage: "Please rephrase it and try again.",
      configurationFailureTitle: "AI service configuration is not ready",
      configurationFailureMessage: "The live AI service is not ready. Your question remains on this page; contact an administrator with the support code.",
      connectionFailureTitle: "Connection interrupted; save not confirmed",
      connectionFailureMessage: "Your question remains on this page. Restore your connection, then retry it.",
      unknownFailureTitle: "AI cannot reply right now",
      unknownFailureMessage: "Your question remains on this page. Retry shortly; if the issue continues, provide the support code.",
      supportCode: (diagnosticId) => `Support code: ${diagnosticId}`,
      copySupportCode: "Copy support code",
      supportCodeCopied: "Support code copied",
      supportCodeCopyFailed: "Copy failed. Select the support code manually.",
      retryAction: "Retry",
      rewriteAction: "Rewrite question",
      retryQuestion: "Retry this question",
      rewriteQuestion: "Rewrite this question",
      assistant: "AI teaching assistant",
      avatar: (_agentId, label) => `${label} university-education avatar`,
      attachmentUnavailable: "The selected file cannot be uploaded.",
      inputRequired: "Enter your thoughts before sending.",
      requestIdentityUnavailable: "This browser cannot create a secure request identifier. Update your browser and try again.",
      requestAccepted: "CAAIS received your request; the multi-agent flow is working on it.",
      attachmentLimit: (maxFiles) => `You can upload up to ${maxFiles} files at once.`,
      fileReadFailed: "The file could not be read.",
      agentLabels: {
        A1: "Xiao Zhang",
        A2: "Professor",
        A3: "Supervision Agent",
        A4: "Reflection Agent",
      },
    },
    content: {
      resize: "Resize the learning-content panel",
      panel: "Learning content and documents",
      displayTab: "Learning content",
      editorTab: "Document editor",
      saveAndClose: "Save and close",
      downloading: "Preparing download...",
      download: "Download to device",
      displayNav: "Learning content",
      backToDisplay: "Back to learning content",
      back: "Back",
      documentFolder: (title) => `Saved document: ${title}`,
      items: {
        platform: {
          label: "About CAAIS",
          body: "CAAIS is an AI-enabled learning platform built on Cognitive Apprenticeship theory…",
        },
        theory: {
          label: "Task cards",
          body: "Complete the Cognitive Apprenticeship tasks in order. Finishing the current task unlocks the next one.",
        },
        history: {
          label: "Saved documents",
          body: "Saved documents preserve the learning process, important materials, and records available for a later pilot-study review.",
        },
      },
      taskCards: {
        listLabel: "Cognitive Apprenticeship task cards",
        progress: (completed, total) => `${completed} of ${total} tasks completed`,
        ordinal: (index) => `Task ${index}`,
        phase: {
          training: "Training task",
          practice: "Practice task",
        },
        status: {
          locked: "Locked",
          available: "Ready",
          active: "In progress",
          completed: "Completed",
        },
        lockedHint: "Complete the previous task to unlock this one",
        enter: "Open task",
        continue: "Continue task",
        review: "Review task",
        complete: "Complete task",
        completing: "Updating...",
        actionFailed: "The task status could not be updated. Please try again.",
        lockedButton: (title) => `${title}, locked`,
        enterButton: (title) => `Open task: ${title}`,
        continueButton: (title) => `Continue task: ${title}`,
        reviewButton: (title) => `Review task: ${title}`,
        completeButton: (title) => `Complete task: ${title}`,
      },
    },
    editor: {
      titleLabel: "Document title",
      titlePlaceholder: "Enter a title...",
      toolbarLabel: "Document formatting tools",
      fontLabel: "Font",
      fontFamilies: {
        system: "System",
        serif: "Serif",
        mono: "Monospace",
      },
      sizeLabel: "Text size",
      bold: "Bold",
      italic: "Italic",
      underline: "Underline",
      alignLeft: "Align left",
      alignCenter: "Align center",
      alignRight: "Align right",
      bulletList: "Bulleted list",
      numberedList: "Numbered list",
      heading1: "Heading 1",
      heading2: "Heading 2",
      heading3: "Heading 3",
      emptyPrompt: "Start writing here...",
      inputLabel: "Write your task understanding, plan, process, or final output here.",
    },
    document: {
      saveQueuedWhileSaving: "The document is saving; your latest change is queued.",
      saveResearchPaused: "The research-recording connection is paused; document changes are still waiting to be saved.",
      saving: "Saving document...",
      saved: "Document saved.",
      saveFailed: "The task-process record could not be saved to the server.",
      archiveFailed: "The document could not be archived. Its workspace content has been retained.",
      saveQueued: "Document changes are waiting to be saved.",
      downloadPreparing: "Preparing download...",
      downloadReady: "Your document download is ready.",
      downloadFailed: "The document could not be downloaded. Please try again shortly.",
      justSaved: "Saved just now",
      untitled: "Untitled document",
    },
    workspace: {
      sessionUnavailable: "The learning-record service is temporarily unavailable. This page will retain your input, but it cannot be saved yet.",
    },
    account: {
      waitForOperation: "Wait for the current save, download, or AI operation to finish before signing out.",
      waitForExportOperation: "Wait for the current save, download, or AI operation to finish before exporting learning data.",
      signingOut: "Signing out...",
      researchSyncRequired: "Research events have not synced safely. Stay online and try signing out again shortly.",
      signOutFailed: "Sign-out did not finish, and the server session is still active. Restore your connection and try again.",
      exporting: "Exporting learning data...",
      exported: "Learning data exported.",
      exportFailed: "Learning data could not be exported. Please try again shortly.",
      deleteConfirmation: "Delete your current learning data? This removes your learning records but does not delete your account.",
      deleting: "Deleting learning data...",
      deleted: "Learning data deleted.",
      deleteFailed: "Learning data could not be deleted. Please try again shortly.",
    },
    researchBoundary: {
      heading: "CAAIS Research Session Protection",
      initializing: "A controlled research session is being established. Please wait.",
      offlineOrTemporary: "The research-record connection is temporarily unavailable. To prevent unrecorded actions, the learning workspace is paused and will resume automatically when the connection is restored.",
      terminalBlocked: "This research session cannot continue. Please stop using the workspace and contact the research team.",
      safeExit: "Exit safely to sign in",
      safeExiting: "Exiting safely...",
      safeExitFailed: "Safe exit is temporarily unavailable. Restore the connection and try again.",
    },
  },
};

export function getLearningCopy(locale: Locale) {
  return learningCopyByLocale[locale];
}

export function getGuideAgentLabel(locale: Locale, agentId: string) {
  return learningCopyByLocale[locale].guide.agentLabels[agentId] ?? agentId;
}
