export const taskFourArtifactMinimumCharacters = 800;
export const pilotTextMinimumCharacters = 8;

export const pilotCopy = {
  "zh-CN": {
    flowEyebrow: "CAAIS 先导学习流程",
    flowHeading: "从专家示范到独立总结",
    teacherReview: "课程内容仍待教师审核；当前仅用于受控先导验证。",
    orientationAction: "我已理解学习流程",
    orientationDone: "启动说明已确认",
    actionSaving: "正在保存...",
    actionFailed: "暂时无法保存，请稍后重试。你的输入仍保留在页面中。",
    expertSpeaker: "教授 · 专家示范",
    expertRole: "本次示范角色",
    expertContext: "示范情境",
    learningDimensions: "三个学习证据维度",
    thinkAloud: "教授的出声思考",
    promptTemplate: "完整提示词示范",
    monitoring: "监控检查点",
    rubric: "输出评价量规",
    expertReviewAction: "我已阅读并比较专家示范",
    expertReviewDone: "专家示范已完成",
    pilotClosed: "先导阶段暂不开放",
    taskDetails: "任务要求",
    evidenceHeading: "完成任务后的学习证据",
    evidenceHelp: "按提示写下你的真实过程。系统会把这些证据保存到当前任务，不会让后台智能体直接替你作答。",
    artifactHeading: "作品证据",
    artifactCount: (count: number) => `当前文档约 ${count} 个字符；需达到 ${taskFourArtifactMinimumCharacters} 个字符，并以后端完成门槛为准。`,
    aiChoiceLegend: "本任务如何使用 GenAI？",
    aiSupported: "使用 GenAI 辅助",
    aiFree: "不使用实时 GenAI",
    aiFreeHelp: "你仍可使用静态专家示范和量规，完成要求与使用 GenAI 时相同。",
    aiChoiceSaving: "正在保存 AI 使用选择...",
    aiChoiceSaved: "AI 使用选择已保存。",
    aiChoiceSaveFailed: "未能保存 AI 使用选择；你的当前选择仍保留在本页，请重试。",
    aiChoiceRetry: "重试保存 AI 使用选择",
    aiChoiceGuideBlocked: "请先保存或重试当前 AI 使用选择，再继续发送导学消息。",
    aiDecisionLegend: "你怎样处理最近一条 AI 建议？",
    aiAccepted: "采纳，并说明依据",
    aiRejected: "不采纳或要求修订，并说明依据",
    aiMessageMissing: "先在左侧与小张或教授交流，得到当前任务的 AI 回复后再记录采纳决定。",
    responseRequired: "请填写这项学习证据。",
    responseTooShort: `请至少填写 ${pilotTextMinimumCharacters} 个字符。`,
    expertComparisonLabel: "与专家过程比较",
    expertComparisonHelp: "写出最明显的差异，以及这一差异对结果的影响。",
    saveEvidence: "保存学习证据",
    evidenceSaved: "学习证据已保存，完成门槛已由服务器重新计算。",
    evidenceConflict: "此任务的学习证据已在其他窗口更新。你的输入仍保留；请刷新后比较并合并，再重新保存。",
    preReflectionHeading: "先完成表达，再查看专家过程对照",
    preReflectionHelp: "先保存作品、规划、监控、评价和任务表达。后台生成对照报告后，Reflection 才会开放。",
    savePreReflectionEvidence: "保存前置证据并生成对照报告",
    reportEyebrow: "后台生成的反思对照报告",
    reportHeading: "专家过程对照",
    reportBasis: "报告只按字段是否有证据进行确定性比较，不展示你的原文，也不作为聊天发言出现。",
    reportArtifactCount: (count: number) => `作品证据：${count} 个字符`,
    reportStructuredCount: (count: number) => `结构化证据：${count} 个字符`,
    reportEvidenceFields: "对应证据",
    reportStatusRecorded: "已有对应证据",
    reportStatusMissing: "尚缺对应证据",
    reflectionUnlocked: "专家过程对照已生成。现在请完成 Reflection，并写出你与专家过程的差异。",
    scaffoldHeading: "小张的分级支架",
    scaffoldRemaining: (remaining: number) => `还可直接求助 ${remaining} 次`,
    scaffoldFading: "直接支架已用完；接下来先说明卡点，再进入自检式帮助。",
    scaffoldEvidenceImproved: (remaining: number) => `证据已有明显进展，本次先减少帮助并进入自检；这不表示已经掌握，仍保留 ${remaining} 次直接辅助。`,
    scaffoldNext: (level: number) => `获取下一步支架（L${level}）`,
    scaffoldResumeDirect: (level: number, remaining: number) => `继续直接求助（L${level}，剩余 ${remaining} 次）`,
    scaffoldSelfCheck: "进入自检式帮助",
    scaffoldReady: (label: string) => `已提供“${label}”支架。`,
    scaffoldLevel: (level: number) => `支架等级 L${level}`,
    completionHeading: "完成前还缺少",
    completionReady: "服务器确认当前任务的必需证据已经齐全。",
    incompleteExit: "结束但标记未完成",
    incompleteWarning: (outcome: "articulation" | "reflection") => outcome === "articulation"
      ? "这会跳过本任务的学习表达并保留缺失项；任务2会标记为未完成，然后继续进入任务4，不会计为达成学习目标。"
      : "这会结束本轮并保留反思等缺失项；系统会明确记录“未完成”，不会把它算作达成学习目标。",
    incompleteBlocked: "还不能确认未完整结束。请先保存并完成以下其他必需证据：",
    reflectionExitLocked: "先完成表达并生成专家过程对照，再选择是否跳过反思。",
    incompleteReason: (outcome: "articulation" | "reflection") => outcome === "articulation"
      ? "如愿意，可说明为什么暂不完成本任务的学习表达"
      : "如愿意，可说明为什么暂不完成反思",
    confirmIncompleteExit: "确认结束并标记未完成",
    cancelIncompleteExit: "继续完成任务",
    incompleteSaved: "本轮已结束并标记为未完成。",
    summaryHeading: "小张 · 总结与结束",
    summaryBody: "回顾这次学习：以后遇到类似任务时，先明确目标和约束，再监控过程，最后用证据评价 AI 输出和自己的成果。",
    summaryAction: "确认总结并结束本轮",
    summaryDone: "本轮总结已确认",
    summaryIncompleteHeading: "本轮已结束，但学习目标未完成",
    summaryIncompleteBody: "缺失证据已保留。你可以在后续重新开始时继续完成反思和其他要求；本轮不会计为证据完整。",
    milestoneStatus: { locked: "未开放", open: "进行中", completed: "已完成" },
  },
  "en-US": {
    flowEyebrow: "CAAIS pilot learning flow",
    flowHeading: "From expert modelling to an independent summary",
    teacherReview: "Teacher review is still pending; this content is for controlled pilot validation only.",
    orientationAction: "I understand the learning flow",
    orientationDone: "Orientation confirmed",
    actionSaving: "Saving...",
    actionFailed: "This could not be saved. Try again shortly; your page input has been retained.",
    expertSpeaker: "Professor · expert model",
    expertRole: "Role in this model",
    expertContext: "Model context",
    learningDimensions: "Three learning-evidence dimensions",
    thinkAloud: "Professor think-aloud",
    promptTemplate: "Complete prompt model",
    monitoring: "Monitoring checkpoints",
    rubric: "Output-evaluation rubric",
    expertReviewAction: "I reviewed and compared the expert model",
    expertReviewDone: "Expert model completed",
    pilotClosed: "Unavailable during the pilot",
    taskDetails: "Task requirements",
    evidenceHeading: "Post-task learning evidence",
    evidenceHelp: "Record your real process. The system saves this evidence to the current task without having a background agent do the work for you.",
    artifactHeading: "Artifact evidence",
    artifactCount: (count: number) => `The current document contains about ${count} characters; it must reach ${taskFourArtifactMinimumCharacters}, and server completion rules remain authoritative.`,
    aiChoiceLegend: "How will you use GenAI in this task?",
    aiSupported: "Use GenAI support",
    aiFree: "Do not use live GenAI",
    aiFreeHelp: "You can still use the static expert model and rubric. The required evidence stays the same.",
    aiChoiceSaving: "Saving the AI-use choice...",
    aiChoiceSaved: "AI-use choice saved.",
    aiChoiceSaveFailed: "The AI-use choice was not saved. Your current page choice is retained; try again.",
    aiChoiceRetry: "Retry saving the AI-use choice",
    aiChoiceGuideBlocked: "Save or retry the current AI-use choice before sending another guide message.",
    aiDecisionLegend: "How did you handle the latest AI suggestion?",
    aiAccepted: "Accept it and explain why",
    aiRejected: "Reject or request revision and explain why",
    aiMessageMissing: "First ask Xiao Zhang or Professor for a reply about this task, then record your decision.",
    responseRequired: "Complete this learning-evidence field.",
    responseTooShort: `Enter at least ${pilotTextMinimumCharacters} characters.`,
    expertComparisonLabel: "Compare with the expert process",
    expertComparisonHelp: "Describe the clearest difference and how it affected the result.",
    saveEvidence: "Save learning evidence",
    evidenceSaved: "Learning evidence saved; the server recalculated the completion gate.",
    evidenceConflict: "This task's evidence changed in another window. Your input is still here; refresh, compare, and merge before saving again.",
    preReflectionHeading: "Articulate first, then review the expert-process comparison",
    preReflectionHelp: "Save the artifact, planning, monitoring, evaluation, and articulation first. Reflection opens after the background report is generated.",
    savePreReflectionEvidence: "Save prerequisite evidence and generate comparison",
    reportEyebrow: "Background-generated reflection comparison report",
    reportHeading: "Expert-process comparison",
    reportBasis: "The report deterministically checks field presence. It does not show your raw text or appear as a chat turn.",
    reportArtifactCount: (count: number) => `Artifact evidence: ${count} characters`,
    reportStructuredCount: (count: number) => `Structured evidence: ${count} characters`,
    reportEvidenceFields: "Linked evidence",
    reportStatusRecorded: "Evidence recorded",
    reportStatusMissing: "Evidence missing",
    reflectionUnlocked: "The expert-process comparison is ready. Complete Reflection and describe how your process differs from the expert model.",
    scaffoldHeading: "Xiao Zhang's tiered scaffolds",
    scaffoldRemaining: (remaining: number) => `${remaining} direct assists remain`,
    scaffoldFading: "Direct scaffolds are used up. Describe where you are stuck before entering self-check support.",
    scaffoldEvidenceImproved: (remaining: number) => `Your evidence clearly improved, so this request fades to self-check. This does not mean mastery; ${remaining} direct assists remain.`,
    scaffoldNext: (level: number) => `Get the next scaffold (L${level})`,
    scaffoldResumeDirect: (level: number, remaining: number) => `Continue direct support (L${level}, ${remaining} remaining)`,
    scaffoldSelfCheck: "Enter self-check support",
    scaffoldReady: (label: string) => `The “${label}” scaffold is ready.`,
    scaffoldLevel: (level: number) => `Scaffold level L${level}`,
    completionHeading: "Still needed before completion",
    completionReady: "The server confirms that all required task evidence is present.",
    incompleteExit: "End and mark incomplete",
    incompleteWarning: (outcome: "articulation" | "reflection") => outcome === "articulation"
      ? "This skips the Task 2 articulation, retains the missing item, marks Task 2 incomplete, and continues to Task 4 without counting the learning goal as met."
      : "This ends the cycle while retaining the missing reflection evidence. It is explicitly incomplete and does not count as meeting the learning goal.",
    incompleteBlocked: "You cannot confirm an incomplete exit yet. Save and complete these other required items first:",
    reflectionExitLocked: "Complete the articulation and generate the expert-process comparison before deciding whether to skip reflection.",
    incompleteReason: (outcome: "articulation" | "reflection") => outcome === "articulation"
      ? "Optionally explain why you are not completing the Task 2 articulation now"
      : "Optionally explain why you are not completing the reflection now",
    confirmIncompleteExit: "Confirm end and mark incomplete",
    cancelIncompleteExit: "Continue the task",
    incompleteSaved: "This cycle ended and was marked incomplete.",
    summaryHeading: "Xiao Zhang · Summary and close",
    summaryBody: "For similar work, clarify the goal and constraints, monitor the process, and use evidence to evaluate both AI output and your own artifact.",
    summaryAction: "Acknowledge the summary and close this cycle",
    summaryDone: "Summary acknowledged",
    summaryIncompleteHeading: "This cycle ended without completing the learning goal",
    summaryIncompleteBody: "The missing evidence is retained. You can complete the reflection and other requirements in a future cycle; this cycle is not evidence-complete.",
    milestoneStatus: { locked: "Not open", open: "In progress", completed: "Completed" },
  },
} as const;
